# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Wed Feb 15 17:09:43 2012

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class DisplayFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DisplayFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.DisplayFrame_statusbar = self.CreateStatusBar(1, 0)
        self.DisplayCtrl = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE | wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DisplayFrame.__set_properties
        self.SetTitle("Display")
        self.SetSize((349, 299))
        self.DisplayFrame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        DisplayFrame_statusbar_fields = ["Application running"]
        for i in range(len(DisplayFrame_statusbar_fields)):
            self.DisplayFrame_statusbar.SetStatusText(DisplayFrame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DisplayFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.DisplayCtrl, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class DisplayFrame
