# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Tue Feb 14 15:38:25 2012

import wx

# begin wxGlade: dependencies
from MainPanel import MainPanel
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.MainPanel = MainPanel(self, -1)
        
        # Menu Bar
        self.MainFrame_menubar = wx.MenuBar()
        self.File = wx.Menu()
        self.MainFrame_menubar.Append(self.File, "File")
        self.SetMenuBar(self.MainFrame_menubar)
        # Menu Bar end
        self.MainFrame_statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("SinFrog")
        self.MainFrame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        MainFrame_statusbar_fields = ["MainFrame_statusbar"]
        for i in range(len(MainFrame_statusbar_fields)):
            self.MainFrame_statusbar.SetStatusText(MainFrame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        MainSizer = wx.BoxSizer(wx.VERTICAL)
        MainSizer.Add(self.MainPanel, 1, wx.EXPAND, 0)
        self.SetSizer(MainSizer)
        MainSizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MainFrame
