#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Tue Feb 14 15:38:25 2012

import wx
from MainFrame import MainFrame

class SinFrog(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        FirstFrame = MainFrame(None, -1, "")
        self.SetTopWindow(FirstFrame)
        FirstFrame.Show()
        return 1

# end of class SinFrog

if __name__ == "__main__":
    SinFrog = SinFrog(0)
    SinFrog.MainLoop()
